# Site settings
title:          Senthilkumar Subrmanian
description:    "Front end Developer"
baseurl:        ""
url:            "https://senthil090.github.io"

# Google Analytics
google_analytics: UA-127658739-1

# Author
author:
  name:        Senthilkumar S
  url:          https://senthil090.github.io
  email:        senthil24jun@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
